import { getInstitution } from "./institutions";
import type { FitLabel, JobFamily, PositionType, Role, Variant } from "./types";

type Draft = {
  id: string;
  title: string;
  inst: string;
  campus?: string;
  family: JobFamily;
  type: PositionType;
  variant: Variant;
  batch: string;
  dir: string;
  stem?: string;
  url?: string;
  jobNo?: string;
  salaryMin?: number;
  salaryMax?: number;
  fit: FitLabel;
  gaps: string[];
  angle: string;
  recommend?: boolean;
  inScope?: boolean;
  hasPacket?: boolean;
  cvFile?: string;
  clFile?: string;
};

const AUG = "1 - Aug 25 apps";

function augStem(title: string, instShort: string) {
  return `${title} - ${instShort}`;
}

const DRAFTS: Draft[] = [
  // —— August 25 NJ staff batch ——
  {
    id: "aug25-ccm-ai-career-coach",
    title: "AI Career Coach",
    inst: "ccm",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("AI Career Coach", "CCM"),
    fit: "moderate",
    gaps: ["No dedicated career-services title"],
    angle:
      "Frame HCL intake automation and KPI dashboards as career-coaching operations: high-volume advising analogue, not a counseling license.",
  },
  {
    id: "aug25-fdu-advisor-florham",
    title: "Academic Advisor",
    inst: "fdu",
    campus: "Florham",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Academic Advisor Florham", "FDU"),
    fit: "moderate",
    gaps: ["No formal academic-advising title"],
    angle:
      "Lead with at-risk student identification, records infrastructure, and committee documentation rather than caseload advising hours.",
  },
  {
    id: "aug25-fdu-advisor-metro",
    title: "Academic Advisor",
    inst: "fdu",
    campus: "Metro",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Academic Advisor Metro", "FDU"),
    fit: "moderate",
    gaps: ["No formal academic-advising title"],
    angle:
      "Same advising analogue as Florham, with Metro's urban/adult-learner mix as the operational difference.",
  },
  {
    id: "aug25-caldwell-academic-coach",
    title: "Academic Coach",
    inst: "caldwell",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Academic Coach", "Caldwell"),
    fit: "moderate",
    gaps: ["No coaching certification named"],
    angle:
      "Position as structured academic-success operations: intake, follow-up cadence, and documentation.",
  },
  {
    id: "aug25-felician-success-coach",
    title: "Academic Success Coach",
    inst: "felician",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Academic Success Coach", "Felician"),
    fit: "moderate",
    gaps: ["No student-affairs title"],
    angle:
      "Catholic-mission institution — address mission directly. Lean on identification of at-risk students and documentation.",
  },
  {
    id: "aug25-fdu-admin-dss",
    title: "Administrative Assistant, Academic DSS",
    inst: "fdu",
    campus: "Florham",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Admin Asst Acad DSS Florham", "FDU"),
    fit: "moderate",
    gaps: ["Title sits below current trajectory unless used as a foot-in-the-door at FDU"],
    angle:
      "Disability-services operations: records, intake, accommodations logistics. Name that the level is a stretch downward.",
  },
  {
    id: "aug25-caldwell-admissions",
    title: "Admissions Counselor",
    inst: "caldwell",
    family: "admissions",
    type: "staff-ft",
    variant: "admissions",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Admissions Counselor", "Caldwell"),
    fit: "moderate",
    gaps: ["No admissions-office experience"],
    angle:
      "Territory communication, events, and CRM-adjacent systems work from the IPG rollout — not travel recruiting stories.",
  },
  {
    id: "aug25-felician-assoc-dir-ops",
    title: "Associate Director, Academic Operations",
    inst: "felician",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Assoc Dir Academic Operations", "Felician"),
    fit: "strong",
    gaps: ["No Banner; title is associate director — confirm level is in scope"],
    angle:
      "Closest ops archetype. Scheduling, vendor payments, adjunct support, accreditation documentation.",
  },
  {
    id: "aug25-hccc-career-transfer",
    title: "Associate Director, Career & Transfer",
    inst: "hccc",
    family: "advising",
    type: "staff-ft",
    variant: "admissions",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Assoc Dir Career Transfer", "Hudson CC"),
    fit: "moderate",
    gaps: ["No career-services or transfer-credit title"],
    angle:
      "Enrollment-adjacent student movement: records, intake, and advising operations at a community college.",
  },
  {
    id: "aug25-fdu-alumni",
    title: "Assistant Director, Alumni Engagement",
    inst: "fdu",
    family: "other",
    type: "staff-ft",
    variant: "admissions",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Asst Dir Alumni Engagement", "FDU"),
    fit: "moderate",
    gaps: ["No advancement / alumni-relations title"],
    angle:
      "Events, relationship systems, and communications. Assistant-director level is in scope.",
  },
  {
    id: "aug25-hccc-nursing-asst-dir",
    title: "Assistant Director, Nursing Program",
    inst: "hccc",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Asst Dir Nursing Program", "Hudson CC"),
    fit: "long-shot",
    gaps: ["No nursing credential; program-director adjacent"],
    angle:
      "Academic-operations support to a professional program, not clinical leadership. Name the credential gap.",
    recommend: false,
  },
  {
    id: "aug25-felician-res-life",
    title: "Assistant Director, Residence Life",
    inst: "felician",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Asst Director Residence Life", "Felician"),
    fit: "moderate",
    gaps: ["No residence-life title"],
    angle:
      "Student-staff oversight, on-call operations, and documentation. Catholic-mission angle.",
  },
  {
    id: "aug25-fdu-cps",
    title: "Assistant to the Director, CPS",
    inst: "fdu",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Asst to Director CPS", "FDU"),
    fit: "moderate",
    gaps: ["Support title may sit below trajectory"],
    angle:
      "Continuing-education operations: scheduling, honoraria, vendor payments, records.",
  },
  {
    id: "aug25-montclair-budget",
    title: "Budget Analyst",
    inst: "montclair",
    family: "budget",
    type: "staff-ft",
    variant: "budget",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Budget Analyst", "Montclair"),
    fit: "strong",
    gaps: [
      "Bachelor's is Business/Marketing, not Finance",
      "No Banner Finance",
      "MBA is Organizational Management",
    ],
    angle:
      "Lead with the $50M budget committee chairmanship and quarterly reviews. Name credential and Banner gaps plainly. Tier-1 institution.",
  },
  {
    id: "aug25-ccm-bizdev",
    title: "Business Development Coordinator",
    inst: "ccm",
    family: "other",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Business Dev Coordinator", "CCM"),
    fit: "moderate",
    gaps: ["More workforce/partnerships than the three archetypes"],
    angle:
      "Employer partnerships and program intake. CCM is Tier 1 — keep unless the posting is sales-shaped.",
  },
  {
    id: "aug25-fdu-dss-coord",
    title: "Coordinator, Disability Support Services",
    inst: "fdu",
    campus: "Florham",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Coordinator DSS", "FDU Florham"),
    fit: "moderate",
    gaps: ["No DSS / ADA-coordinator title"],
    angle:
      "Accommodations operations, records, and intake. Coordinator level is on-trajectory.",
  },
  {
    id: "aug25-felician-sas",
    title: "Coordinator, Student Academic Services",
    inst: "felician",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Coordinator SAS", "Felician"),
    fit: "moderate",
    gaps: ["No SAS title"],
    angle: "Academic-services operations at a Catholic institution. Mission-affirmative.",
  },
  {
    id: "aug25-ccm-culinary-dir",
    title: "Culinary Center Director",
    inst: "ccm",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Culinary Center Director", "CCM"),
    fit: "long-shot",
    gaps: ["Director-level; culinary subject matter"],
    angle: "Out of locked scope (director-and-above). Skip unless operator overrides.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-kean-dean-health",
    title: "Dean, Health Professions",
    inst: "kean",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Dean Health Professions", "Kean"),
    fit: "long-shot",
    gaps: ["Executive; health-professions dean"],
    angle: "Hard-filter fail: executive. Archive, do not walk unless overridden.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-montclair-deans-ops",
    title: "Dean's Office Operations Coordinator",
    inst: "montclair",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Deans Office Ops Coordinator", "Montclair"),
    fit: "strong",
    gaps: ["No dean's-office title"],
    angle:
      "Pure academic-ops archetype at a Tier-1. Scheduling, honoraria, adjunct support, accreditation paper.",
  },
  {
    id: "aug25-montclair-planned-giving",
    title: "Director, Major & Planned Giving",
    inst: "montclair",
    family: "other",
    type: "exec",
    variant: "admissions",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Dir Major Planned Giving", "Montclair"),
    fit: "long-shot",
    gaps: ["Director-and-above; no gift-officer track"],
    angle: "Out of locked scope. Skip.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-kean-public-safety",
    title: "Director of Operations, Public Safety",
    inst: "kean",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Dir Operations Public Safety", "Kean"),
    fit: "long-shot",
    gaps: ["Director-level; public-safety operations"],
    angle: "Out of locked scope. Skip.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-fdu-enrollment-analytics",
    title: "Enrollment Analytics Coordinator",
    inst: "fdu",
    family: "admissions",
    type: "staff-ft",
    variant: "admissions",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Enrollment Analytics Coord", "FDU"),
    fit: "strong",
    gaps: ["No Slate / Banner; no enrollment-reporting title"],
    angle:
      "KPI dashboards and records infrastructure as the admissions-analytics analogue. Name CRM gaps.",
  },
  {
    id: "aug25-hccc-exec-rn",
    title: "Executive Director, RN Programs",
    inst: "hccc",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Exec Dir RN Programs", "Hudson CC"),
    fit: "long-shot",
    gaps: ["Executive; nursing program leadership"],
    angle: "Hard-filter fail: executive. Archive.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-montclair-exec-ops",
    title: "Executive Operations Assistant",
    inst: "montclair",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Exec Operations Asst", "Montclair"),
    fit: "moderate",
    gaps: ["Assistant title may sit below trajectory"],
    angle:
      "Dean's-office / cabinet operations at Tier-1. Strong ops analogue; watch the level.",
  },
  {
    id: "aug25-caldwell-finaid",
    title: "Financial Aid Counselor",
    inst: "caldwell",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Financial Aid Counselor", "Caldwell"),
    fit: "moderate",
    gaps: ["No financial-aid title or Title IV experience"],
    angle:
      "Regulatory reporting and records as the analogue. Name the Title IV gap outright.",
  },
  {
    id: "aug25-caldwell-hr",
    title: "HR Coordinator",
    inst: "caldwell",
    family: "other",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("HR Coordinator", "Caldwell"),
    fit: "moderate",
    gaps: ["No HRIS / HR-coordinator title"],
    angle: "Hiring support, onboarding, records. Adjacent to adjunct-hiring operations.",
  },
  {
    id: "aug25-kean-reslife-mng",
    title: "Managing Assistant Director, Residence Life",
    inst: "kean",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Managing Asst Dir Res Life", "Kean"),
    fit: "moderate",
    gaps: ["No residence-life title"],
    angle: "Student-staff oversight and operations. Assistant-director level is in scope.",
  },
  {
    id: "aug25-kean-fire-safety",
    title: "Managing Assistant Director, Fire Safety",
    inst: "kean",
    family: "other",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Mng Asst Dir Fire Safety", "Kean"),
    fit: "long-shot",
    gaps: ["Fire-safety / EHS subject matter"],
    angle: "Operations management analogue only. Weak family match — likely skip.",
    recommend: false,
  },
  {
    id: "aug25-kean-reslife-mng-2",
    title: "Managing Assistant Director, Residence Life",
    inst: "kean",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Mng Asst Dir Residence Life", "Kean"),
    fit: "moderate",
    gaps: ["Possible duplicate of the other Kean res-life posting"],
    angle: "Confirm against the first Kean res-life packet before applying twice.",
  },
  {
    id: "aug25-caldwell-procurement",
    title: "Procurement Coordinator",
    inst: "caldwell",
    family: "budget",
    type: "staff-ft",
    variant: "budget",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Procurement Coordinator", "Caldwell"),
    fit: "moderate",
    gaps: ["No Unimarket / procurement-card title"],
    angle:
      "Vendor payments and purchasing operations from the academic-ops analogue. Name Unimarket gap.",
  },
  {
    id: "aug25-kean-rhd",
    title: "Residence Hall Director",
    inst: "kean",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Residence Hall Director", "Kean"),
    fit: "moderate",
    gaps: ["Live-in role; no RHD title"],
    angle: "Live-in student-staff operations. Confirm housing requirement before walking.",
  },
  {
    id: "aug25-hccc-advising-training",
    title: "Senior Assistant Director, Advising Training",
    inst: "hccc",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Sr Asst Dir Advising Training", "Hudson CC"),
    fit: "moderate",
    gaps: ["No advising-training title"],
    angle:
      "Training 600 users on Salesforce/Dynamics is the proof. Advising operations, not counseling.",
  },
  {
    id: "aug25-fdu-capital",
    title: "Senior Manager, Capital Projects",
    inst: "fdu",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Sr Mgr Capital Projects", "FDU"),
    fit: "long-shot",
    gaps: ["Facilities / capital-projects; manager-and-above"],
    angle: "Out of locked scope. Skip.",
    inScope: false,
    recommend: false,
  },
  {
    id: "aug25-caldwell-accountant",
    title: "Staff Accountant",
    inst: "caldwell",
    family: "budget",
    type: "staff-ft",
    variant: "budget",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Staff Accountant", "Caldwell"),
    fit: "moderate",
    gaps: ["Degree is not Accounting; no titled accountant years"],
    angle:
      "Regulatory reporting and monthly close analogue. Name the credential gap. Watch that the level may be a step down.",
  },
  {
    id: "aug25-montclair-student-services",
    title: "Student Services Specialist",
    inst: "montclair",
    family: "student-services",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Student Services Specialist", "Montclair"),
    fit: "moderate",
    gaps: ["Specialist title may sit below trajectory"],
    angle: "Tier-1 student-services operations. Strong family match, watch the level.",
  },
  {
    id: "aug25-ccm-virtual-campus",
    title: "Virtual Campus Coordinator",
    inst: "ccm",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "aug-25",
    dir: AUG,
    stem: augStem("Virtual Campus Coordinator", "CCM"),
    fit: "strong",
    gaps: ["No LMS-administration title named"],
    angle:
      "Online-operations coordination at Tier-1 CCM. Scheduling, records, and student intake.",
  },

  // —— Seton Hall packets ——
  {
    id: "shu-10-lecturer-bio",
    title: "Full-Time Lecturer, Biological Sciences",
    inst: "shu",
    family: "faculty",
    type: "faculty",
    variant: "ops",
    batch: "shu-v1",
    dir: "SetonHall-Apps-v1/10 - Full Time Lecturer Biological Sciences",
    jobNo: "497046",
    url: "https://jobs.shu.edu/en-us/job/497046/full-time-lecturer-biological-sciences",
    fit: "long-shot",
    gaps: [
      "Ph.D. in biological sciences required",
      "No biology teaching load",
    ],
    angle:
      "State the subject-matter disqualification. Only the service/assessment dimensions are honest.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-12-asst-prof-cs",
    title: "Assistant Professor, Computer Science",
    inst: "shu",
    family: "faculty",
    type: "faculty",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/12 - Assistant Professor Computer Science",
    fit: "long-shot",
    gaps: ["Full-time faculty; CS Ph.D. not attested"],
    angle: "Hard-filter fail: faculty.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-13-asst-prof-law",
    title: "Assistant Professor, Law and Politics",
    inst: "shu",
    family: "faculty",
    type: "faculty",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/13 - Assistant Professor Law and Politics",
    fit: "long-shot",
    gaps: ["Full-time faculty"],
    angle: "Hard-filter fail: faculty.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-14-adjunct-arabic",
    title: "Adjunct Instructor, Arabic",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/14 - Adjunct Instructor Arabic",
    fit: "long-shot",
    gaps: ["Adjunct stream deferred; subject-matter"],
    angle: "Deferred until a discipline list is locked.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-15-adjunct-biz-writing",
    title: "Adjunct Professor of Business Writing",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/15 - Adjunct Professor of Business Writing",
    fit: "moderate",
    gaps: ["Adjunct stream deferred"],
    angle:
      "Closest adjunct to the corpus (business writing). Still deferred unless operator opens the adjunct stream.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-16-adjunct-japanese",
    title: "Adjunct Instructor, Japanese",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/16 - Adjunct Instructor Japanese",
    fit: "long-shot",
    gaps: ["Adjunct deferred; language instruction"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-17-contract-bio",
    title: "Contract Faculty, Biological Sciences",
    inst: "shu",
    family: "faculty",
    type: "faculty",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/17 - Contract Faculty Biological Sciences",
    fit: "long-shot",
    gaps: ["Faculty; biology"],
    angle: "Hard-filter fail: faculty.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-18-adjunct-writing",
    title: "Adjunct Professor, Writing",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/18 - Adjunct Professor Writing",
    fit: "moderate",
    gaps: ["Adjunct deferred"],
    angle: "Deferred. Revisit with the discipline list.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-19-adjunct-ethics",
    title: "Adjunct Professor, Ethics",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/19 - Adjunct Professor Ethics",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-20-adjunct-itm",
    title: "Adjunct Professor, Information Technology Management",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/20 - Adjunct Professor Information Technology Management",
    fit: "moderate",
    gaps: ["Adjunct deferred"],
    angle:
      "Closest IT-management adjunct. Still deferred unless the adjunct stream opens.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-21-adjunct-psych",
    title: "Adjunct Instructor, Professional Psychology and Family Therapy",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/21 - Adjunct Instructor Professional Psychology and Family Therap",
    fit: "long-shot",
    gaps: ["Adjunct deferred; licensure"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-22-adjunct-core",
    title: "Adjunct Faculty, University Core Curriculum",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v2",
    dir: "SetonHall-Apps-v2/22 - Adjunct Faculty University Core Curriculum",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-23-adjunct-k12",
    title: "Adjunct Instructor, K-12 Education Leadership",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/23 - Adjunct Instructor K-12 Education Leadership Programs",
    fit: "long-shot",
    gaps: ["Adjunct deferred; K-12 leadership"],
    angle: "K-12 is out of sector even if adjunct opens.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-24-adjunct-hed-leadership",
    title: "Adjunct Instructor, Higher Education Leadership",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/24 - Adjunct Instructor Higher Education Leadership Programs",
    fit: "moderate",
    gaps: ["Adjunct deferred"],
    angle:
      "Closest adjunct to the staff search. Revisit when the adjunct stream opens.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-25-museum",
    title: "Adjunct Instructor, Museum Professions",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/25 - Adjunct Instructor Museum Professions",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-26-art-history",
    title: "Adjunct Instructor, Art History",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/26 - Adjunct Instructor Art History",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-27-foundations-art",
    title: "Adjunct Instructor, Foundations Fine Art",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/27 - Adjunct Instructor Foundations Fine Art",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-28-animation",
    title: "Adjunct Instructor, Animation and Game Design",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/28 - Adjunct Instructor Animation and Game Design",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-29-advertising",
    title: "Adjunct Instructor, Advertising and Design",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/29 - Adjunct Instructor Advertising and Design",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-30-theatre",
    title: "Adjunct Instructor, Theatre",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/30 - Adjunct Instructor Theatre",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-31-music",
    title: "Adjunct Instructor, Music",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/31 - Adjunct Instructor Music",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-32-journalism",
    title: "Adjunct Instructor, Journalism",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v3",
    dir: "SetonHall-Apps-v3/32 - Adjunct Instructor Journalism",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-33-sports-media",
    title: "Adjunct Instructor, Sports Media",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/33 - Adjunct Instructor Sports Media",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-34-communication",
    title: "Adjunct Instructor, Communication",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/34 - Adjunct Instructor Communication",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-36-oral-comm",
    title: "Adjunct Instructor, Oral Communication",
    inst: "shu",
    family: "adjunct",
    type: "adjunct",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/36 - Adjunct Instructor Oral Communication",
    fit: "long-shot",
    gaps: ["Adjunct deferred"],
    angle: "Deferred.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-37-budget-analyst",
    title: "Senior Budget Analyst",
    inst: "shu",
    family: "budget",
    type: "staff-ft",
    variant: "budget",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/37 - Senior Budget Analyst",
    jobNo: "497461",
    url: "https://jobs.shu.edu/en-us/job/497461/senior-budget-analyst",
    salaryMin: 65000,
    salaryMax: 85000,
    fit: "moderate",
    gaps: [
      "Bachelor's is not Finance/Accounting",
      "Five years in a titled finance role not attested",
      "No Banner Finance",
      "MBA is Organizational Management",
    ],
    angle:
      "Lead with the $50M budget committee chairmanship and quarterly reviews, then regulatory reporting and dashboards. Name credential and Banner gaps.",
    recommend: true,
  },
  {
    id: "shu-40-immigration-fellow",
    title: "Immigration Detention Fellow",
    inst: "shu",
    family: "other",
    type: "temp",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/40 - Immigration Detention Fellow",
    fit: "long-shot",
    gaps: ["Fellowship; legal clinic subject matter"],
    angle: "Out of family. Skip unless operator wants the SHU network play.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-41-prehealth",
    title: "Pre-Health Advisor",
    inst: "shu",
    family: "advising",
    type: "staff-ft",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/41 - Pre-Health Advisor",
    fit: "moderate",
    gaps: ["No pre-health advising title; packet may be incomplete"],
    angle:
      "Advising operations and records. Adjacent family — digest-tier, not top.",
    hasPacket: false,
    recommend: true,
  },
  {
    id: "shu-42-ug-admissions",
    title: "Assistant Director, Undergraduate Admissions",
    inst: "shu",
    family: "admissions",
    type: "staff-ft",
    variant: "admissions",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/42 - Assistant Director Undergraduate Admissions",
    jobNo: "497383",
    url: "https://careers.pageuppeople.com/763/cw/en-us/job/497383/assistant-director-undergraduate-admissions",
    salaryMin: 47000,
    salaryMax: 57000,
    fit: "moderate",
    gaps: [
      "No admissions-office years (posting allows a related higher degree to substitute)",
      "No Banner or Slate (desired only)",
    ],
    angle:
      "Lean on staff oversight, records-system design, program-activity data, and territory communication — not recruiting travel. SHU affinity is usable here.",
    recommend: true,
  },
  {
    id: "shu-43-buyer",
    title: "Buyer",
    inst: "shu",
    family: "budget",
    type: "staff-ft",
    variant: "budget",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/43 - Buyer",
    fit: "moderate",
    gaps: ["No Unimarket / buyer title"],
    angle:
      "Procurement and vendor-payment analogue from academic operations. Name the purchasing-system gap.",
    recommend: true,
  },
  {
    id: "shu-44-assoc-dean-nursing",
    title: "Associate Dean, Nursing Research and Graduate Department",
    inst: "shu",
    family: "other",
    type: "exec",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/44 - Associate Dean Nursing Research and Graduate Department",
    fit: "long-shot",
    gaps: ["Associate dean; nursing"],
    angle: "Hard-filter fail: executive.",
    inScope: false,
    recommend: false,
  },
  {
    id: "shu-45-ops-natural-sciences",
    title: "Operations Manager, Natural Sciences Unit",
    inst: "shu",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/45 - Operations Manager Natural Sciences Unit",
    fit: "strong",
    gaps: ["No Banner; manager title — confirm it is not director-and-above"],
    angle:
      "Closest academic-ops package at SHU: scheduling, vendor payments, adjunct support, unit operations.",
    recommend: true,
  },
  {
    id: "shu-46-simulation-ops",
    title: "Simulation Operations Specialist",
    inst: "shu",
    family: "academic-ops",
    type: "staff-ft",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/46 - Simulation Operations Specialist",
    fit: "moderate",
    gaps: ["Clinical-simulation subject matter"],
    angle:
      "Operations and systems analogue, not clinical. Honest if the posting is equipment/scheduling-heavy.",
    recommend: true,
  },
  {
    id: "shu-48-corp-foundations",
    title: "Associate Director, Corporate and Foundation Relations",
    inst: "shu",
    family: "other",
    type: "staff-ft",
    variant: "admissions",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/48 - Assoc Director Corporate and Foundation Relations",
    fit: "moderate",
    gaps: ["No gift-officer / foundation-relations title"],
    angle:
      "Relationship systems and proposal operations. Assistant/associate director is in scope; family is adjacent.",
    recommend: true,
  },
  {
    id: "shu-51-grad-ops",
    title: "Assistant Director, Grad Operations",
    inst: "shu",
    family: "admissions",
    type: "staff-ft",
    variant: "ops",
    batch: "shu-v4",
    dir: "SetonHall-Apps-v4/51 - Assistant Director Grad Operations",
    jobNo: "497033",
    url: "https://jobs.shu.edu/en-us/job/497033/assistant-director-grad-operations",
    fit: "moderate",
    gaps: [
      "No Technolutions Slate (stated requirement)",
      "No Ellucian Banner (preferred)",
      "Experience is higher-ed operations, not admissions operations",
    ],
    angle:
      "CRM/ERP administrator moving into enrollment operations. Name Slate and Banner outright; answer with the record of learning unfamiliar platforms.",
    recommend: true,
  },
];

function toRole(d: Draft): Role {
  const inst = getInstitution(d.inst);
  const inScope =
    d.inScope ??
    (d.type !== "faculty" && d.type !== "adjunct" && d.type !== "exec");
  const stem = d.stem;
  const folder = d.dir.split("/").pop() ?? "";
  const shuTitle = folder.replace(/^\d+\s-\s/, "");
  const shuCv = d.dir.startsWith("SetonHall")
    ? `${d.dir}/Resume - Max Oza - ${shuTitle}.docx`
    : undefined;
  const shuCl = d.dir.startsWith("SetonHall")
    ? `${d.dir}/Cover Letter - Max Oza - ${shuTitle}.docx`
    : undefined;
  return {
    id: d.id,
    title: d.title,
    institutionId: d.inst,
    campus: d.campus,
    family: d.family,
    positionType: d.type,
    variant: d.variant,
    modality: "onsite",
    batch: d.batch,
    githubDir: d.dir,
    cvFile: d.cvFile ?? (stem ? `${d.dir}/CV - ${stem}.docx` : shuCv),
    clFile: d.clFile ?? (stem ? `${d.dir}/CL - ${stem}.docx` : shuCl),
    applyUrl: d.url ?? inst.careersUrl,
    jobNo: d.jobNo,
    salaryMin: d.salaryMin,
    salaryMax: d.salaryMax,
    fitLabel: d.fit,
    gaps: d.gaps,
    angle: d.angle,
    recommend: d.recommend ?? inScope,
    inScope,
    hasPacket: d.hasPacket ?? true,
  };
}

export const ROLES: Role[] = DRAFTS.map(toRole);

export const ROLES_BY_ID: Record<string, Role> = Object.fromEntries(
  ROLES.map((r) => [r.id, r]),
);

export function getRole(id: string): Role | undefined {
  return ROLES_BY_ID[id];
}

export const FAMILY_LABEL: Record<JobFamily, string> = {
  admissions: "Admissions / enrollment",
  "academic-ops": "Academic operations",
  budget: "Budget / finance",
  registrar: "Registrar",
  "student-services": "Student services",
  advising: "Advising",
  faculty: "Faculty",
  adjunct: "Adjunct",
  other: "Other",
};

export const VARIANT_LABEL: Record<Variant, string> = {
  admissions: "Admissions CV",
  ops: "Academic ops CV",
  budget: "Budget / finance CV",
};
